version: 2
dist: build
builds:
  - binary: rds_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -v
    ldflags:
        - -s -w
        - -X github.com/prometheus/common/version.Version={{ .Version }}
        - -X github.com/prometheus/common/version.Revision={{ .ShortCommit }}
        - -X github.com/prometheus/common/version.Branch={{ .Branch }}
        - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
snapshot:
  version_template: "{{ .ShortCommit }}"
changelog:
  disable: true
release:
  github:
    owner: petsinc
    name: rds_exporter
  draft: true
  prerelease: auto
dockers_v2:
  - images:
      - "ghcr.io/petsinc/rds_exporter"
    tags:
      - "{{.Major}}.{{.Minor}}"
      - "{{.Version}}"
    dockerfile: Dockerfile.releaser
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
