version: 2

dist: build
builds:
  - binary: rds_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -v
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .ShortCommit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true

snapshot:
  name_template: "{{ .ShortCommit }}"

release:
  github:
    owner: petsinc
    name: rds_exporter
  draft: true
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/petsinc/rds_exporter:{{.Major}}.{{.Minor}}"
      - "ghcr.io/petsinc/rds_exporter:{{.Version}}"
    dockerfile: Dockerfile.releaser
    use: buildx
